services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chatnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./chat-frontend:/app
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://chat-backend:8000
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
